- _posts/2015-04-03-sat2015-cfp.md
> Added SAT 2015 second call for papers announcement.

- _posts/2015-04-23-sat2015-cfp.md
> Added post for SAT'15 abstract and paper deadline extension.

- about.md
This about page is saying that we should look to the Wikipedia Page. 
Let's make it simple, and let's give directly the link to do it ;)
> Add a link to the Wikipedia page.

- _includes/header.html
- _posts/2015-07-15-FoSSaCS-2016.md
- index.html
* Add of the news FoSSaCS (04/2016, Netherlands about modal logic) 
* Fix of this 'active' class on the Home page
> Add of FoSSaCS news + fix of this "active" class on the Home page.

- _posts/2015-08-19-sat2015-reg.md
Added post about early registration ending and student grants for SAT 2015
> Added post about early registration ending and student grants for SAT 2015

- _posts/2015-07-13-Advances-in-Modal-Logic-2016.md
Description about this event + CFP
> Update information about AiML

- _posts/2017-04-03-JAR-special-issue-cfp.md
It looks good to me (and it works).
> JAR Special Issue on Automated Reasoning Systems

- _includes/head.html
The title of the website is appearing now, before it was written 'Home'.
Moreover, there is now a favicon also, it is for now the design of the SAT association. 
But hey, it's something :).
> TItle of the website is appearing now + Favicon.

- _posts/2019-01-17-sat19-cfw.md
Hi Daniel. Please, merge the following pull request. :) It is a call for SAT 2019 workshops.
> Added SAT 2019 CFW.

- _posts/2019-02-04-sat19-cfp.md
Hi Daniel. Could you, please, merge this and recompile satlive.org?
> Added SAT 2019 CFP.

- _posts/2019-02-26-sat19-final-cfp.md
Hi Daniel. Could you, please, merge this final call for papers to SAT 2019? Thanks.
> SAT 2019 final call for papers.

- _posts/2019-03-25-school19.md
Hi Daniel, could you, please, merge this into the master branch and put it on the website? This is the announcement of the open registration for the SAT/SMT/AR Summer School 2019. Thanks!
> Registration at SAT/SMT/AR Summer School 2019.

- _posts/2019-04-24-QBF2019-CfP.md
Hi Daniel! I added the call for papers for the QBF Workshop. Could you please post it on the website? Thanks!
> Added QBF'19 CfP

- _posts/2019-05-05-sat19-reg.md
This is a call for participation for SAT 2019. Could you, please, merge it?
> Added SAT 2019 call for participation.

- _posts/2019-05-17-QBF2019-CfP-extended.md
Hi Daniel,
We extended the deadline for the QBF Workshop. Could you please post this for me?
Thanks,
Florian
> QBF'19 extended deadline

- _posts/2019-06-19-sat19-final.md
Hi Daniel,
Could you, please, merge the following commit? This is the final call for participation for SAT 2019.
Best,
Alexey
> Added the final call for participation for SAT 2019.

- _posts/2019-12-17-sat20-cfw.md
Hi Daniel,
Could you please post the SAT 2020 call for workshops on SATLive?
Thanks and best regards,
Florian
> SAT 2020 call for workshops

- _posts/2020-06-10-ictai20-cfp.md
Please Daniel, can you broadcast this CFP?
JM
> CFP Ictai 2020. 

- _posts/2021-11-29-core-challenge.md
Dear Daniel, 
We are holding a competition named "Core Challenge 2022" which is about combinatorial reconfiguration. 
Please add our news to the web page of SATLIVE!
Best regards,
Takehide
> add news 2021-11-29

- _posts/2022-02-08-position-monash.md
This post is to announce a recent opening at Monash University.
> Added the announcement of a position at Monash.

- _posts/2022-03-07.md
Here's a CFP for the SMT workshop, I'm hoping you'd like to spread the word through sat live!  Let me know if I should fix something.
> CFP for SMT 2022

- _posts/2023-01-20-SAT23-CFP.md
> SAT 2023 CFP

- _posts/2023-03-16-cp23-cfp.md
The CP 2023 Call for Papers, including a fast track for papers rejected from SAT.
> CP 2023 CfP

- _posts/2023-07-26-cp23-cfpart.md
> Adding Call for Participation for CP 2023.

- _posts/2024-01-18-sat24-cfw.md
Hi Daniel,
This is an announcement of the Call for Workshops for SAT'24. Could you please merge it? 🙂 Thanks!
Best,
Alexey
> Added SAT24 Call for Workshops.

- _posts/2024-03-28-pos24-cfp.md
Could you please merge this PR? It adds a CFP for Pragmatics of SAT 2024. Thanks!
> Added POS24 CFP.

- _posts/2024-10-02-satres-phd.md
> Call for applications: SAtRes PhD position KIT, October 2024

- _posts/2025-05-13-smt25-cfp.md
This is a new post on SAT Live to announce a deadline extension for SMT 2025.
> deadline extension for SMT 2025
